### ISSUE TITLE
Add corresponding removal scripts

### ISSUE THREAD

**Issue by ergonlogic** [hashicorp/puppet-bootstrap#29]
In some cases, such as Packer builds of Docker images, using Puppet for initial configuration is great. But since there's no intention of running Puppet after the initial build, its preferable to remove Puppet from the system. This is probably a simple one-liner for all the distros, but it'd be nice to have them all documented somewhere. For Debian/Ubuntu ones it'd probably just be:

    apt-get purge -y --auto-remove puppet

**Comment by grubernaut** [comment]
This would probably be best used as an inline shell command inside of a packer template, and is out of the scope of this project (which is to install puppet) :)
