### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by judywawira** [hashicorp/puppet-bootstrap#38]
I get this error when using this script 

==> default: /tmp/vagrant-shell: line 1: /vagrant/puppet_bootstrap.sh: Permission denied
==> default: /tmp/vagrant-shell: line 3: puppet: command not found
==> default: /tmp/vagrant-shell: line 4: puppet: command not found
==> default: /tmp/vagrant-shell: line 5: puppet: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

my vagrantfile is as below

 config.vm.provision :shell do |shell|
    shell.inline = "/vagrant/puppet_bootstrap.sh;
                    mkdir -p /etc/puppet/modules;
                    puppet module install puppetlabs/git;
                    puppet module install puppetlabs/mysql;
                    puppet module install puppetlabs-tomcat;"
  end

**Comment by shadowdoc** [comment]
Check the permissions on the puppet_bootstrap.sh file to make sure that it has Execute permission:

chmod +x puppet_boostrap.sh 
or
chmod 755 puppet_bootstrap.sh

**Comment by grubernaut** [comment]
This should be fixed with #42
