### ISSUE TITLE
CentOS: wget must be installed

### ISSUE THREAD

**Issue by zouzias** [hashicorp/puppet-bootstrap#39]
The "wget" package must be installed before executing the following line 

https://github.com/hashicorp/puppet-bootstrap/blob/master/centos_6_x.sh#L22

Similarly, for the other versions of CentOS.

**Comment by robinbowes** [comment]
Alternatively, use "curl" which *is* installed by default.

**Comment by grubernaut** [comment]
`curl` isn't installed on debian or ubuntu by default, but wget is.

Following the README of the project, I'd be happy to switch CentOS over to using curl, if you have the free time to write up a small PR for that?
