### ISSUE TITLE
Q: Why install RubyGems in addition to Puppet in ubuntu.sh?

### ISSUE THREAD

**Issue by miller-productions** [hashicorp/puppet-bootstrap#47]
Hi there,

Thanks for the great Puppet bootstrap scripts, they are very helpful indeed.

I was just looking through the one named `ubuntu.sh` and noticed the block at the bottom where you also install RubyGems. i.e.

```
# Install RubyGems for the provider
echo "Installing RubyGems..."
if [ $DISTRIB_CODENAME != "trusty" ]; then
  apt-get install -y rubygems >/dev/null
fi
gem install --no-ri --no-rdoc rubygems-update
update_rubygems >/dev/null
```

I am wondering why you do this? Not being that familiar with Puppet yet, I'm not really sure how RubyGems supports Puppet and why it is needed? I have looked around various docs but haven't yet found anything concrete.

Thanks for your time and thoughts.

Cheers,
Dan

**Comment by grubernaut** [comment]
Rubygems was a requirement puppet-agent as of Puppet - 3.5.1. 

I don't believe this is still the case, and that the RubyGems dependency can fully be removed, but I'll have to verify this for sure. 

Removing the RubyGems dependency definitely allows for newer versions of Puppet to run and work without the rubygems dependency.
