### ISSUE TITLE
Puppet .deb files have different name

### ISSUE THREAD

**Issue by renegat59** [hashicorp/puppet-bootstrap#58]
The script ubuntu.sh is trying to get file:
http://apt.puppetlabs.com/puppetlabs-release-xenial.deb
but it doesnt exists. The correct path is:
http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb

**Comment by grubernaut** [comment]
Hey there @renegat59, thanks for the issue!

Referring to the comments at the top of the script: 
```
# This bootstraps Puppet on Ubuntu 12.04 LTS.
#
# To try puppet 4 -->  PUPPET_COLLECTION=pc1 ./ubuntu.sh
```
We can set the environment variable `PUPPET_COLLECTION=pc1` to install later versions of puppet. 
Please let me know if you have any further questions, would be happy to help!
